
# ---- configuration ----

# exclude bundle files
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor
  - Submodules
  - README.md
  - '*/README.md'
  - '*/LICENSE'

timezone: Asia/Tokyo
encording: utf-8

# ---- gems ------------

plugins:
  - jekyll-gist
  - jekyll-mentions
  - jekyll-feed

# ---- jekyll-feed -----
feed : 
  path : atom.xml

# ---- collections -----

collections :
  docs :
    output    : true
    permalink : /:path

# ---- build option ----

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed

# ---- fixed github metadata authentication bug ----
#github : [metadata]
