
# ---- configuration ----

# exclude bundle files
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: Asia/Tokyo
encording: utf-8

# ---- collections -----

collections :
  Jekyll:
    output: true
  VimR:
    output: true
  Bootstrap:
    output: true
  RaspberryPi:
    output: true
  VirtualBox:
    output: true


# ---- build option ----

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed
