
# ---- configuration ----

# exclude bundle files
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: Asia/Tokyo
encording: utf-8

# ---- gems ------------

gems:
  - jekyll-gist

# ---- collections -----

collections :
  docs :
    output    : true
    permalink : /:path

# ---- build option ----

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed

# ---- fixed github metadata authentication bug ----
github : [metadata]
