
# ---- configuration ----

# exclude bundle files
exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: Asia/Tokyo
encording: utf-8

# ---- gems ------------

gems:
  - jekyll-gist

# ---- collections -----

collections :
  Jekyll:
    output: true
  VimR:
    output: true
  Bootstrap:
    output: true
  RaspberryPi:
    output: true
  VirtualBox:
    output: true
  Cpp:
    output: true
  LibCurl:
    output: true
  JavaScript:
    output: true
  OpenFrameworks:
    output: true
  Live:
    output: true
  Max:
    output: true
  Mac:
    output: true
  Memo:
    output: true

# ---- build option ----

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed
